// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/yckao/drone-convert-advanced/cmd/drone-convert-advanced/config"
	"github.com/yckao/drone-convert-advanced/service/commit"
)

// Injectors from wire.go:

func InitializeApplication(config2 config.Config) (application, error) {
	mainHealthzHandler := provideHealth()
	client := provideClient(config2)
	commitService := commit.New(client)
	repositoryService := provideRepositoryService(client, config2)
	fileService := provideContentService(client)
	convertService := provideStarlarkPlugin(client, fileService, commitService)
	server := provideConvert(commitService, repositoryService, convertService, config2)
	mux := provideRouter(mainHealthzHandler, server)
	serverServer := provideServer(mux, config2)
	mainApplication := newApplication(serverServer)
	return mainApplication, nil
}
